# Note Pytorch

## 1. Tensor

- Khởi tạo

In [15]:
import torch

a = torch.tensor([1,2,3,4,5,6])
b = torch.arange(0,6)

print(a)
print(b)

tensor([1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5])


Các phép toán

In [16]:
c = a + b
print(a, b, c)
c = a.add(b)
print(a,b,c)
a.add_(b)
print(a,b,c)
# Tương tự có
# a.mul_()
# a.sub_()


tensor([1, 2, 3, 4, 5, 6]) tensor([0, 1, 2, 3, 4, 5]) tensor([ 1,  3,  5,  7,  9, 11])
tensor([1, 2, 3, 4, 5, 6]) tensor([0, 1, 2, 3, 4, 5]) tensor([ 1,  3,  5,  7,  9, 11])
tensor([ 1,  3,  5,  7,  9, 11]) tensor([0, 1, 2, 3, 4, 5]) tensor([ 1,  3,  5,  7,  9, 11])


Reshape mảng, việc thay đổi trên mảng mới -> ảnh hưởng đến mảng bản đầu


In [22]:
d = torch.tensor([1,2,3,4,5,6,7,8])
c = d.view(2,4)
print(c)
c = d.view(-1,4)
e = d.view(-1,2)
print(c)
c +=1
print(c)
print(d)
print(e)


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[2, 3, 4, 5],
        [6, 7, 8, 9]])
tensor([2, 3, 4, 5, 6, 7, 8, 9])
tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


Để không làm ảnh hưởng đến mảng ban đầu => tạo bản copy mảng

In [27]:
test = torch.arange(0,9)
copy = torch.clone(test)
copy +=1
print(copy)
print(test)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


```Chú ý: Với các hàm có dạng func_(), có dấu "_" ở đuôi => có nghĩa là sẽ modified giá trị của biến gọi hàm. Ví dụ: a.mul_(b) => a = a*b. ```

## 2. Gradient calculator với autograd


Để thực hiện tính toán grad cho một hàm nào đó

Ví dụ: f = x^2

=> grad(f) = 2*x

Thực hiện bằng code:

In [39]:
x = torch.arange(1,4,dtype=torch.float32, requires_grad=True)
f = x**2
f = f.mean()
print(f)
f.backward()
print(f)
print(x.grad)

tensor(4.6667, grad_fn=<MeanBackward0>)
tensor(4.6667, grad_fn=<MeanBackward0>)
tensor([0.6667, 1.3333, 2.0000])


Cần define `requires_grad=True` và gọi `.backward()` để tính.

Lưu ý, ví dụ trên là thực hiện với f mang scalar value (f.mean()) Cho nên `f.backward()` không có parameter.

Xét ví dụ:

In [38]:
x = torch.arange(1,4,dtype=torch.float32, requires_grad=True)
f = 2*x
# f = f.mean()
print(f)
f.backward(torch.tensor([0.1, 1.0, 0.001],dtype=torch.float32))
print(f)
print(x.grad)

tensor([2., 4., 6.], grad_fn=<MulBackward0>)
tensor([2., 4., 6.], grad_fn=<MulBackward0>)
tensor([0.2000, 2.0000, 0.0020])


Cần truyền vector vào hàm `backward`.

Trong quá trình training model, khi tính toán lại weights... Có những lúc ta không muốn tính toán gradient. Ta có các cách sau:

```Python
x.requires_grad_(False)
# Hoặc
y = x.detach()
```

Trong đó cả 2 hàm đều tạo ra biến mới với `require_grad=False`

Hoặc

```Python
with torch.no_grad():
    ...
```

Reset grad về 0:

```Python
x.grad.zero_()
```

## 3. Gradient Descent with Autograd and Backpropagation
